// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechStore.Api.Common.Data;

#nullable disable

namespace TechStore.Api.Common.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Api.Catalog.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_categories_parent_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_categories_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("TechStore.Api.Catalog.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSerialTracked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_serial_tracked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("specs")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("idx_products_barcode");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_products_category_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("idx_products_sku");

                    b.HasIndex("Specs")
                        .HasDatabaseName("idx_products_specs_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Specs"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Specs"), new[] { "jsonb_path_ops" });

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_base_price_ge_zero", "base_price >= 0");

                            t.HasCheckConstraint("ck_products_cost_price_ge_zero", "cost_price >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Catalog.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("specs")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variant_name");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("idx_product_variants_barcode");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_product_variants_product_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("idx_product_variants_sku");

                    b.HasIndex("Specs")
                        .HasDatabaseName("idx_product_variants_specs_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Specs"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Specs"), new[] { "jsonb_path_ops" });

                    b.HasIndex("Id", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_product_variants_id_product");

                    b.ToTable("product_variants", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_variants_price_ge_zero", "price >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Customers.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("LoyaltyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("loyalty_points");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Standard")
                        .HasColumnName("tier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("idx_customers_phone");

                    b.HasIndex("Tier")
                        .HasDatabaseName("idx_customers_tier");

                    b.ToTable("customers", null, t =>
                        {
                            t.HasCheckConstraint("ck_customers_dob_valid", "date_of_birth <= CURRENT_DATE");

                            t.HasCheckConstraint("ck_customers_loyalty_points_ge_zero", "loyalty_points >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Customers.Entities.CustomerLoyaltyPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PointsChange")
                        .HasColumnType("integer")
                        .HasColumnName("points_change");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_cust_loyalty_customer_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_cust_loyalty_order_id");

                    b.ToTable("customer_loyalty_points", null, t =>
                        {
                            t.HasCheckConstraint("ck_cust_loyalty_balance_after_ge_zero", "balance_after >= 0");

                            t.HasCheckConstraint("ck_cust_loyalty_points_change_not_zero", "points_change <> 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Customers.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Percentage")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_discount_amount");

                    b.Property<decimal>("MinOrderAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("min_order_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("usage_limit");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("used_count");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_vouchers_code");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("idx_vouchers_active")
                        .HasFilter("is_active = true");

                    b.ToTable("vouchers", null, t =>
                        {
                            t.HasCheckConstraint("ck_vouchers_discount_value_valid", "discount_value > 0 AND (discount_type <> 'Percentage' OR discount_value <= 100)");

                            t.HasCheckConstraint("ck_vouchers_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("ck_vouchers_max_discount_ge_zero", "max_discount_amount IS NULL OR max_discount_amount >= 0");

                            t.HasCheckConstraint("ck_vouchers_min_order_ge_zero", "min_order_amount >= 0");

                            t.HasCheckConstraint("ck_vouchers_usage_limit_gt_zero", "usage_limit > 0");

                            t.HasCheckConstraint("ck_vouchers_used_count_valid", "used_count >= 0 AND used_count <= usage_limit");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.HasIndex("UserId", "TokenHash")
                        .HasDatabaseName("idx_refresh_tokens_active")
                        .HasFilter("is_revoked = false");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TechStore.Api.Identity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("TechStore.Api.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TechStore.Api.Identity.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("InventoryStockId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_stock_id");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("movement_type");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<Guid?>("OrderReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_return_id");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid?>("PurchaseOrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_item_id");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_after");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_change");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("idx_inventory_movements_order_item_id");

                    b.HasIndex("OrderReturnId")
                        .HasDatabaseName("idx_inventory_movements_return_id");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("idx_inventory_movements_user_id");

                    b.HasIndex("PurchaseOrderItemId")
                        .HasDatabaseName("idx_inventory_movements_po_item_id");

                    b.HasIndex("InventoryStockId", "CreatedAt")
                        .HasDatabaseName("idx_inventory_movements_stock_created_at");

                    b.ToTable("inventory_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movements_qty_after_ge_zero", "quantity_after >= 0");

                            t.HasCheckConstraint("ck_inventory_movements_qty_change_not_zero", "quantity_change <> 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.InventoryStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MinStockAlert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("min_stock_alert");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_inventory_stocks_variant_id");

                    b.HasIndex("ProductId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("idx_inventory_stocks_product_variant");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ProductId", "VariantId"), false);

                    b.HasIndex("VariantId", "ProductId");

                    b.ToTable("inventory_stocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_stocks_min_alert_ge_zero", "min_stock_alert >= 0");

                            t.HasCheckConstraint("ck_inventory_stocks_quantity_ge_zero", "quantity >= 0");

                            t.HasCheckConstraint("ck_inventory_stocks_reserved_ge_zero", "reserved_quantity >= 0");

                            t.HasCheckConstraint("ck_inventory_stocks_reserved_le_quantity", "reserved_quantity <= quantity");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("OrderedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ordered_at");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<Guid?>("ReceivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_cost");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_purchase_orders_created_by");

                    b.HasIndex("PoNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_purchase_orders_po_number");

                    b.HasIndex("ReceivedByUserId")
                        .HasDatabaseName("idx_purchase_orders_received_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_purchase_orders_status");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("idx_purchase_orders_supplier_id");

                    b.ToTable("purchase_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_orders_total_cost_ge_zero", "total_cost >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("ordered_quantity");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("ReceivedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("received_quantity");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_po_items_product_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("idx_po_items_po_id");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_po_items_variant_id");

                    b.HasIndex("VariantId", "ProductId");

                    b.HasIndex("PurchaseOrderId", "ProductId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("uq_po_items_order_product_variant");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("PurchaseOrderId", "ProductId", "VariantId"), false);

                    b.ToTable("purchase_order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_po_items_ordered_qty_gt_zero", "ordered_quantity > 0");

                            t.HasCheckConstraint("ck_po_items_received_qty_valid", "received_quantity >= 0 AND received_quantity <= ordered_quantity");

                            t.HasCheckConstraint("ck_po_items_unit_cost_ge_zero", "unit_cost >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.SerialImei", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Imei")
                        .HasColumnType("text")
                        .HasColumnName("imei");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("InStock")
                        .HasColumnName("status");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<DateTime?>("WarrantyEndAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("warranty_end_at");

                    b.Property<int>("WarrantyMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("warranty_months");

                    b.Property<DateTime?>("WarrantyStartAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("warranty_start_at");

                    b.HasKey("Id");

                    b.HasIndex("Imei")
                        .IsUnique()
                        .HasDatabaseName("idx_serial_imeis_imei");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_serial_imeis_product_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("idx_serial_imeis_po_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_serial_imeis_serial");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_serial_imeis_variant_id");

                    b.HasIndex("Id", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_serial_imeis_id_product");

                    b.HasIndex("ProductId", "Status")
                        .HasDatabaseName("idx_serial_imeis_instock")
                        .HasFilter("status = 'InStock'");

                    b.HasIndex("VariantId", "ProductId");

                    b.ToTable("serial_imeis", null, t =>
                        {
                            t.HasCheckConstraint("ck_serial_imeis_identifier_present", "NULLIF(BTRIM(serial_number), '') IS NOT NULL OR NULLIF(BTRIM(imei), '') IS NOT NULL");

                            t.HasCheckConstraint("ck_serial_imeis_imei_format", "imei IS NULL OR imei ~ '^[0-9]{15}$'");

                            t.HasCheckConstraint("ck_serial_imeis_unit_cost", "unit_cost IS NULL OR unit_cost >= 0");

                            t.HasCheckConstraint("ck_serial_imeis_warranty_months", "warranty_months >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .HasDatabaseName("idx_suppliers_phone");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("TechStore.Api.Orders.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CashierUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_user_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Cash")
                        .HasColumnName("payment_method");

                    b.Property<Guid?>("PosSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pos_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id");

                    b.HasIndex("CashierUserId")
                        .HasDatabaseName("idx_orders_cashier_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_orders_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_orders_customer_id");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("idx_orders_code");

                    b.HasIndex("PosSessionId")
                        .HasDatabaseName("idx_orders_session_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.HasIndex("VoucherId")
                        .HasDatabaseName("idx_orders_voucher_id");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_discount_amount_ge_zero", "discount_amount >= 0");

                            t.HasCheckConstraint("ck_orders_subtotal_ge_zero", "subtotal >= 0");

                            t.HasCheckConstraint("ck_orders_tax_amount_ge_zero", "tax_amount >= 0");

                            t.HasCheckConstraint("ck_orders_total_amount_ge_zero", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Orders.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SerialImeiId")
                        .HasColumnType("uuid")
                        .HasColumnName("serial_imei_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("VariantName")
                        .HasColumnType("text")
                        .HasColumnName("variant_name");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_order_items_product_id");

                    b.HasIndex("SerialImeiId")
                        .HasDatabaseName("idx_order_items_serial_imei_id");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_order_items_variant_id");

                    b.HasIndex("Id", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_items_id_order");

                    b.HasIndex("OrderId", "SerialImeiId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_items_order_serial");

                    b.HasIndex("SerialImeiId", "ProductId");

                    b.HasIndex("VariantId", "ProductId");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("chk_order_items_serial_single_unit", "serial_imei_id IS NULL OR quantity = 1");

                            t.HasCheckConstraint("ck_order_items_discount_ge_zero", "discount_amount >= 0");

                            t.HasCheckConstraint("ck_order_items_quantity_gt_zero", "quantity > 0");

                            t.HasCheckConstraint("ck_order_items_total_price_ge_zero", "total_price >= 0");

                            t.HasCheckConstraint("ck_order_items_unit_cost_valid", "unit_cost IS NULL OR unit_cost >= 0");

                            t.HasCheckConstraint("ck_order_items_unit_price_ge_zero", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Orders.Entities.OrderReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRestocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_restocked");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<Guid>("ProcessedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("processed_by_user_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<string>("RefundMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refund_method");

                    b.Property<Guid?>("RefundPosSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_pos_session_id");

                    b.Property<DateTime>("RefundedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("refunded_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_returns_order_id");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("idx_order_returns_item_id");

                    b.HasIndex("ProcessedByUserId")
                        .HasDatabaseName("idx_order_returns_user_id");

                    b.HasIndex("RefundPosSessionId")
                        .HasDatabaseName("idx_order_returns_refund_session_id");

                    b.HasIndex("RefundedAt")
                        .HasDatabaseName("idx_order_returns_refunded_at");

                    b.HasIndex("OrderItemId", "OrderId");

                    b.ToTable("order_returns", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_returns_qty_gt_zero", "quantity > 0");

                            t.HasCheckConstraint("ck_order_returns_refund_amt_ge_zero", "refund_amount >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Sales.Entities.PosSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("CardSalesTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("card_sales_total");

                    b.Property<decimal>("CashSalesTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cash_sales_total");

                    b.Property<Guid>("CashierUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_user_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<decimal?>("ClosingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("closing_balance");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("OpenedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("opened_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("OpeningBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("opening_balance");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VietQrSalesTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("vietqr_sales_total");

                    b.HasKey("Id");

                    b.HasIndex("CashierUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_pos_sessions_cashier_open")
                        .HasFilter("status = 'Open'");

                    b.HasIndex("OpenedAt")
                        .HasDatabaseName("idx_pos_sessions_opened_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_pos_sessions_status");

                    b.ToTable("pos_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_pos_sessions_card_sales_ge_zero", "card_sales_total >= 0");

                            t.HasCheckConstraint("ck_pos_sessions_cash_sales_ge_zero", "cash_sales_total >= 0");

                            t.HasCheckConstraint("ck_pos_sessions_opening_ge_zero", "opening_balance >= 0");

                            t.HasCheckConstraint("ck_pos_sessions_vietqr_sales_ge_zero", "vietqr_sales_total >= 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Sales.Entities.VietQrTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankBin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_bin");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("PosSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pos_session_id");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("provider_transaction_id");

                    b.Property<string>("QrContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_content");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId")
                        .HasDatabaseName("idx_vietqr_tx_confirmed_by");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_vietqr_tx_expires_at");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("uq_vietqr_confirmed_order")
                        .HasFilter("status = 'Confirmed'");

                    b.HasIndex("PosSessionId")
                        .HasDatabaseName("idx_vietqr_tx_session_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_vietqr_tx_status");

                    b.HasIndex("TransactionCode")
                        .IsUnique()
                        .HasDatabaseName("idx_vietqr_tx_code");

                    b.HasIndex("Provider", "ProviderTransactionId")
                        .IsUnique()
                        .HasDatabaseName("uq_vietqr_provider_transaction");

                    b.ToTable("vietqr_transactions", null, t =>
                        {
                            t.HasCheckConstraint("chk_vietqr_confirmation_evidence", "(status = 'Confirmed' AND confirmed_at IS NOT NULL AND (confirmed_by_user_id IS NOT NULL OR provider_transaction_id IS NOT NULL)) OR (status <> 'Confirmed' AND confirmed_at IS NULL AND confirmed_by_user_id IS NULL)");

                            t.HasCheckConstraint("chk_vietqr_expiry_after_creation", "expires_at > created_at");

                            t.HasCheckConstraint("chk_vietqr_provider_reference_pair", "(provider IS NULL) = (provider_transaction_id IS NULL)");

                            t.HasCheckConstraint("ck_vietqr_tx_amount_gt_zero", "amount > 0");
                        });
                });

            modelBuilder.Entity("TechStore.Api.Catalog.Entities.Category", b =>
                {
                    b.HasOne("TechStore.Api.Catalog.Entities.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TechStore.Api.Catalog.Entities.Product", b =>
                {
                    b.HasOne("TechStore.Api.Catalog.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechStore.Api.Catalog.Entities.ProductVariant", b =>
                {
                    b.HasOne("TechStore.Api.Catalog.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechStore.Api.Customers.Entities.CustomerLoyaltyPoint", b =>
                {
                    b.HasOne("TechStore.Api.Customers.Entities.Customer", "Customer")
                        .WithMany("LoyaltyPointsHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TechStore.Api.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("TechStore.Api.Identity.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechStore.Api.Identity.Entities.UserRole", b =>
                {
                    b.HasOne("TechStore.Api.Identity.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Identity.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.InventoryMovement", b =>
                {
                    b.HasOne("TechStore.Api.Inventory.Entities.InventoryStock", "InventoryStock")
                        .WithMany("Movements")
                        .HasForeignKey("InventoryStockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Identity.Entities.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Inventory.Entities.PurchaseOrderItem", "PurchaseOrderItem")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InventoryStock");

                    b.Navigation("PerformedByUser");

                    b.Navigation("PurchaseOrderItem");
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.InventoryStock", b =>
                {
                    b.HasOne("TechStore.Api.Catalog.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Catalog.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("TechStore.Api.Identity.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Identity.Entities.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechStore.Api.Inventory.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("TechStore.Api.Catalog.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Inventory.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Catalog.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.SerialImei", b =>
                {
                    b.HasOne("TechStore.Api.Catalog.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Inventory.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechStore.Api.Catalog.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("TechStore.Api.Orders.Entities.Order", b =>
                {
                    b.HasOne("TechStore.Api.Identity.Entities.User", "CashierUser")
                        .WithMany()
                        .HasForeignKey("CashierUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Customers.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechStore.Api.Customers.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CashierUser");

                    b.Navigation("Customer");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("TechStore.Api.Orders.Entities.OrderItem", b =>
                {
                    b.HasOne("TechStore.Api.Orders.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Catalog.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Inventory.Entities.SerialImei", "SerialImei")
                        .WithMany()
                        .HasForeignKey("SerialImeiId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechStore.Api.Catalog.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId", "ProductId")
                        .HasPrincipalKey("Id", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("SerialImei");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("TechStore.Api.Orders.Entities.OrderReturn", b =>
                {
                    b.HasOne("TechStore.Api.Orders.Entities.Order", "Order")
                        .WithMany("Returns")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Identity.Entities.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Orders.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId", "OrderId")
                        .HasPrincipalKey("Id", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderItem");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("TechStore.Api.Sales.Entities.PosSession", b =>
                {
                    b.HasOne("TechStore.Api.Identity.Entities.User", "CashierUser")
                        .WithMany()
                        .HasForeignKey("CashierUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashierUser");
                });

            modelBuilder.Entity("TechStore.Api.Sales.Entities.VietQrTransaction", b =>
                {
                    b.HasOne("TechStore.Api.Identity.Entities.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechStore.Api.Orders.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechStore.Api.Sales.Entities.PosSession", "PosSession")
                        .WithMany("VietQrTransactions")
                        .HasForeignKey("PosSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("Order");

                    b.Navigation("PosSession");
                });

            modelBuilder.Entity("TechStore.Api.Catalog.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("TechStore.Api.Catalog.Entities.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("TechStore.Api.Customers.Entities.Customer", b =>
                {
                    b.Navigation("LoyaltyPointsHistory");
                });

            modelBuilder.Entity("TechStore.Api.Identity.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TechStore.Api.Identity.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.InventoryStock", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TechStore.Api.Inventory.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("TechStore.Api.Orders.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Returns");
                });

            modelBuilder.Entity("TechStore.Api.Sales.Entities.PosSession", b =>
                {
                    b.Navigation("VietQrTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
